version: "3"

services:
  neo4j: # Official image available at https://hub.docker.com/_/neo4j
    build: ./neo4j/v4.x.x
    container_name: "neo4j-4.x.x"
    ports:
      - 7474:7474 # HTTP
      - 7473:7473 # HTTPS
      - 7687:7687 # Bolt
    environment:
      # See https://neo4j.com/docs/operations-manual/current/docker/configuration/ for the naming convention for NEO4J settings
      #   As an example, dbms.tx_log.rotation.size would be NEO4J_dbms_tx__log_rotation_size
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true

      # Please set 'dbms.allow_upgrade' to 'true' in your configuration file and try again. Detailed description: Upgrade is required to migrate store to new major version.
      - NEO4J_dbms_allow__upgrade=true

    # Uncomment the following section if you want to persist Neo4j settings and data
    # volumes:
    #   # Stores the authentication and roles for each database, as well as the actual data contents of each database instance (in graph.db folder)
    #   - ./neo4j/tmp/data:/data

    #   # Outputting the Neo4j logs to a place outside the container ensures we can troubleshoot any errors in Neo4j, even if the container crashes.
    #   - ./neo4j/tmp/logs:/logs

    #   # Binds the import directory, so we can copy CSV or other flat files into that directory for importing into Neo4j.
    #   # Load scripts for importing that data can also be placed in this folder for us to execute.
    #   - ./neo4j/tmp/import:/var/lib/neo4j/import

    #   # Sets up our plugins directory. If we want to include any custom extensions or add the Neo4j APOC or graph algorithms library,
    #   # exposing this directory simplifies the process of copying the jars for Neo4j to access.
    #   - ./neo4j/tmp/plugins:/plugins
    # # See https://neo4j.com/developer/docker-run-neo4j/ for additional configuration ideas
